sed -i "/kino/d" temp/list_exclude.csv
sed -i "/loud/d" temp/list_exclude.csv
sed -i "/ront/d" temp/list_exclude.csv
sed -i "/film/d" temp/list_exclude.csv
sed -i "/line/d" temp/list_exclude.csv
sed -i "/azin/d" temp/list_exclude.csv
sed -i "/oker/d" temp/list_exclude.csv
sed -i "/porn/d" temp/list_exclude.csv
sed -i "/seri/d" temp/list_exclude.csv
sed -i "/lord/d" temp/list_exclude.csv
sed -i "/game/d" temp/list_exclude.csv
sed -i "/vest/d" temp/list_exclude.csv
sed -i "/slot/d" temp/list_exclude.csv
sed -i "/play/d" temp/list_exclude.csv
sed -i "/torr/d" temp/list_exclude.csv
sed -i "/trad/d" temp/list_exclude.csv
sed -i "/club/d" temp/list_exclude.csv
sed -i "/mone/d" temp/list_exclude.csv
sed -i "/shop/d" temp/list_exclude.csv
sed -i "/live/d" temp/list_exclude.csv
sed -i "/port/d" temp/list_exclude.csv
sed -i "/rezk/d" temp/list_exclude.csv
sed -i "/mega/d" temp/list_exclude.csv
sed -i "/tion/d" temp/list_exclude.csv
sed -i "/prav/d" temp/list_exclude.csv
sed -i "/inup/d" temp/list_exclude.csv
sed -i "/spin/d" temp/list_exclude.csv
sed -i "/obet/d" temp/list_exclude.csv
sed -i "/ital/d" temp/list_exclude.csv
sed -i "/star/d" temp/list_exclude.csv
sed -i "/gold/d" temp/list_exclude.csv
sed -i "/seed/d" temp/list_exclude.csv
sed -i "/plom/d" temp/list_exclude.csv
sed -i "/utor/d" temp/list_exclude.csv